INSTALL.md: tell people to install bazel
urbit/vere pull request #145
Opened 2023-01-20 01:00 UTC by belisarius222

I was confused when I tried to follow the instructions to build Vere and `bazel` didn't exist on my machine after running the "prerequisites" install command.

2023-01-20 15:27 UTC, mcevoypeter requested changes

2023-01-20 15:27 UTC, mcevoypeter commented on INSTALL.md
> +The first step is to install `bazel` using the instructions found on the [`bazel`][bazel][^1] site.
Can you change `[bazel][bazel]` to `[bazel][bazel-install]` and add `[bazel-install]: https://bazel.build/install` below `[bazel-config]: https://bazel.build/run/bazelrc` at the bottom of the file?

2023-01-21 03:23 UTC, belisarius222 commented
@mcevoypeter PTAL

2023-01-23 16:00 UTC, mcevoypeter approved these changes
LGTM

2023-01-23 16:00 UTC, merged