Don't trigger workflows for any release activities
urbit/vere pull request #152
Opened 2023-01-20 20:24 UTC by matthew-levan

Resolves #150. See the GitHub [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) for additional context.

2023-01-20 20:38 UTC, mcevoypeter requested changes
Once you remove the unnecessary `release: types: []` trigger in `release.yml`, it'll be good to merge. Note that CI is failing due to #148, so once #149 gets merged, rebase on top `develop`, and CI should pass.

2023-01-20 20:38 UTC, mcevoypeter commented on .github/workflows/feature.yml
> -  release: null
Great catch. I missed this in #108.

2023-01-20 20:38 UTC, mcevoypeter commented on .github/workflows/release.yml
> +    types: []
We can remove this since, as you point out, the only jobs triggered are via `feature.yml`.

2023-01-20 20:54 UTC, matthew-levan commented
> Once you remove the unnecessary `release: types: []` trigger in `release.yml`, it'll be good to merge. Note that CI is failing due to #148, so once #149 gets merged, rebase on top `develop`, and CI should pass.

Thank you. I'll rebase once #149 is merged, probably next week. Then we can re-evaluate #57.

2023-01-20 21:07 UTC, mcevoypeter commented
#149 just merged.

2023-01-20 22:27 UTC, matthew-levan commented
Ok, rebase is done. Please feel free to approve and merge @mcevoypeter. Have an excellent weekend!

2023-01-23 16:02 UTC, mcevoypeter approved these changes

2023-01-23 16:02 UTC, merged