Create pull_request_template.md
urbit/vere pull request #171
Opened 2023-01-26 17:39 UTC by barter-simsum

### Description

Resolves #170 

When a PR is created, this should automatically populate as the PR description
comment. If we're trying to adhere to this form, it's probably good to be
reminded of it.

Note, this doesn't take effect unless added to /master.

2023-01-27 15:07 UTC, zalberico requested changes
We probably want the two lines from the docs to also be comments, otherwise seems fine to me. Thanks for thinking of this.

2023-01-27 15:07 UTC, zalberico commented on .github/pull_request_template.md
> +A thorough description of the changes made.
We probably want this to be a comment too.

2023-01-27 15:07 UTC, zalberico commented on .github/pull_request_template.md
> +References to any related issues, links, papers, etc.
Same with this one (comment)

2023-01-27 21:32 UTC, barter-simsum commented
@Fang- , opposed?

2023-01-31 18:22 UTC, Fang- commented
Yes, somewhat opposed. I've voiced my reservations about gh templates in the past. Especially for PRs (as opposed to issues) I think it's fair to expect a higher standard of description without hand-holding the author into it. To me, pre-filled templates always feel oppressive rather than helpful.

Just a gentle nudge to "please review contributing.md" as is at the top here is probably the least invasive thing we could do. As long as that's there, not sure what purpose it serves to also pre-write the section headings. The "Other sections" heading feels doubly out of place, since it's not even in the contributing.md.

Also still not a fan of squash-merging, but perhaps that ship has sailed. Somewhat out of scope for discussion here anyway.

2023-01-31 19:19 UTC, zalberico commented
The main bit I care about is `Fixes: ####` so people remember to put the issue link in there.

2023-01-31 19:19 UTC, barter-simsum commented
@Fang-  I agree. I find pull request templates in general pretty annoying. Often pull request descriptions don't even really line up with the template given. Maybe just including a `Description` header -- does that even add anything? -- and I think the "Resolves#" string is fine to include and serves as a good reminder to link an issue. Will delete all comments etc.

How about that?

2023-01-31 20:36 UTC, barter-simsum commented
The template is now a single line "Resovled #" as a basic reminder to link an issue. Doesn't require any annoying deletion of text from contributor.

@Fang-

2023-01-31 20:39 UTC, zalberico commented
Cool - if we find people leaving the details blank we can ask them to add details (and if necessary introduce some templating if it's an issue).

2023-02-01 16:38 UTC, belisarius222 commented
Should this PR be targeting master, as it is now, or develop?

2023-02-01 16:44 UTC, mcevoypeter commented
It should target `develop`. Good catch, @belisarius222.

2023-02-01 20:12 UTC, mcevoypeter approved these changes

2023-02-01 20:13 UTC, mcevoypeter commented
@Fang- if you feel good about this, we can merge it.

2023-02-07 14:57 UTC, Fang- commented
Sure, this is minimal enough. Looks better!

2023-02-07 19:14 UTC, merged