Alternate fix for #157 urbit play
urbit/vere pull request #210
Opened 2023-02-08 19:16 UTC by sigilante

Resolves #157; see PR #158 for discussion.

Playback is normal speed and Ctrl+Z works to exit without hanging.  This may have inadvertently clobbered some of your replay stuff @mcevoypeter.

After `urbit play` succeeds, it boots into a prompt—not sure if this is desirable behavior or not.

2023-02-10 00:08 UTC, joemfb requested changes
Thanks for restaging this, I'm really glad you got it working.

I've noted some minor things below. Also, please squash these commits down to one, and then merge `develop` back on top.

2023-02-10 00:08 UTC, joemfb commented on pkg/noun/vortex.c
> -
This blank line at the end of the file should be restored.

2023-02-10 00:08 UTC, joemfb commented on pkg/vere/db/lmdb.h
> +
These `lmdb.(c|h)` changes were also copied into #165, which was just merged.

2023-02-10 00:08 UTC, joemfb commented on pkg/vere/main.c
> +#if !defined(U3_OS_mingw)
This `#if` can be removed.

2023-02-10 00:08 UTC, joemfb commented on pkg/vere/mars.c
> +}
The trace module was refactored upstream, so this function should change to match `_serf_step_trace()` (the only difference being that the pier path is passed in).

2023-02-10 00:08 UTC, joemfb commented on pkg/vere/mars.c
> +    if ( c3n == u3_disk_read_meta(log_u, 0, 0, &lif_w) ) {
This signature also has been changed upstream.

2023-02-10 00:08 UTC, joemfb commented on pkg/vere/vere.h
> +        u3_trac    tra_u;                   //  tracing information
This struct member and the declaration can be (re)removed, as the tracing module has been refactored.

2023-02-10 00:11 UTC, joemfb requested changes
I forgot to mention: Please change the `_cw_play()` call site in `_cw_utils()` to return `1` (done) instead of `2` (continue).

2023-02-10 00:12 UTC, joemfb requested changes

2023-02-10 00:12 UTC, joemfb commented on pkg/vere/mars.c
> +  fprintf(stderr, "play (%" PRIu64 ")\r\n", eve_d);
Also, please remove this printf.

2023-02-10 01:59 UTC, sigilante commented
Ah, that's why it was going to the Dojo prompt (1 v 2).

2023-02-10 15:26 UTC, sigilante commented
Well, `git squash` and rebase looks like a royal mess here.

2023-02-10 15:29 UTC, sigilante commented
@matthew-levan try this version now.

@belisarius222 the commit history is a mess here now so I may need you to show me how to rebase this against `develop` with a squash.

2023-02-10 15:58 UTC, matthew-levan commented
@sigilante still hanging for me, on `linux-x86_64` and `macos-aarch64`, unfortunately. My test steps are: boot fresh fakezod, `rm zod/.urb/chk`, `./urbit play zod`.

2023-02-10 18:02 UTC, zalberico commented
Can we fix the off-by-one error Peter fixed in https://github.com/urbit/vere/pull/192 in this one too?

2023-02-10 21:25 UTC, joemfb commented on pkg/vere/main.c
> +#if !defined(U3_OS_mingw)
Sorry for the confusion, I just meant for you to removed the condition, not the code inside of it. That code (setting up the ctrl-z handler) needed to be excluded on windows (which is no longer supported), so it should just be included unconditionally.

2023-02-10 21:34 UTC, joemfb requested changes
Sorry, my comment (https://github.com/urbit/vere/issues/157#issuecomment-1425069566) could've been more clear.

There are a some problems with your fixes in c48cf9807e8673b05e520a97d7f443b446598a83:

- the ctrl-z handler needs to be restored
- the changes to `serf.c` were desirable (`_serf_prof()` was moved to `u3a_prof()`, so should not be restored)
- the usage string that you added back from #192 doesn't not correspond to these arguments

Also, it looks like you rebased or cherry-picked `develop` onto this branch. There are conflict markers in several files, and many more commits than should be present in this PR view. The simplest thing is probably to force push this branch back to c48cf9807e8673b05e520a97d7f443b446598a83 and clean it up, then simply merge.

2023-02-10 21:34 UTC, joemfb commented
@zalberico this PR adds an entirely different replay code path, the only area of overlap is in the interface (the play subcommand itself).

2023-02-10 21:35 UTC, joemfb commented
@matthew-levan can you say any more about your testing? I've built this branch on `macos-aarch64` and replayed without issue.

2023-02-13 18:19 UTC, sigilante commented
Current status:  there is some ongoing discussion in #157 about a discrepancy in playback speed dependent on the pill which boots Arvo.

That rather leads me to believe that what we're seeing with `urbit play` is a consequence not a cause, and we have something else going on that's simply manifesting here.

2023-06-08 15:50 UTC, closed without merging