build: upload soon and edge tags to dockerhub
urbit/vere pull request #258
Opened 2023-02-24 22:59 UTC by ashelkovnykov

Resolves #160

Adds a job which will push a tag with the pace value to DockerHub. Technically also adds a `live` tag which references the same image as the `latest` tag.

2023-02-25 13:17 UTC, matthew-levan approved these changes
LGTM.

2023-02-27 16:15 UTC, mcevoypeter requested changes
Minor request for simplification in `//docker:pace_tag` but otherwise looks good to me.

2023-02-27 16:15 UTC, mcevoypeter commented on docker/BUILD.bazel
> +    $$(tr -d '\n' < $(execpath PACE)) > $@
You can remove the nested evaluation (`$$()`):
```bash
tr -d '\n' < $(execpath PACE) > $@
```
You can also replace `$(execpath PACE)` with `$<`:
```bash
tr -d '\n' < $< > $@

2023-02-27 23:40 UTC, mcevoypeter approved these changes

2023-02-28 22:23 UTC, ashelkovnykov commented
@belisarius222 @jalehman Ready for merge

2023-02-28 22:25 UTC, merged