Add jets for min/max.
urbit/vere pull request #457
Opened 2023-06-14 18:18 UTC by sigilante

Resolves #456.

Written live for a tutorial with @belisarius222

2023-06-14 18:28 UTC, joemfb requested changes
These look good. Kudos for that "cell or zero" crash checks, those are subtle.

A couple nits:

2023-06-14 18:28 UTC, joemfb commented on pkg/noun/jets/a/max.c
> +#define MAX(i, j) (((i) > (j)) ? (i) : (j))
We already have this as `c3_max()`, lets use that.

2023-06-14 18:28 UTC, joemfb commented on pkg/noun/jets/a/max.c
> +      max = (mpz_cmp(a_mp, b_mp) >= 0) ? a : b;
This should be `> 0` for consistency.

2023-06-14 18:28 UTC, joemfb commented on pkg/noun/jets/a/min.c
> +#define MIN(i, j) (((i) < (j)) ? (i) : (j))
`c3_min()`

2023-06-14 18:28 UTC, joemfb commented on pkg/noun/jets/a/min.c
> +      min = (mpz_cmp(a_mp, b_mp) <= 0) ? a : b;
`< 0`

2023-06-14 20:06 UTC, joemfb approved these changes
this will do

2023-06-15 15:37 UTC, merged

2023-06-20 03:17 UTC, ashelkovnykov commented
> Kudos for that "cell or zero" crash checks, those are subtle.

I don't understand - why are the `bail` checks "cell or zero"?