ames: forward iff we're a galaxy
urbit/vere pull request #493
Opened 2023-07-12 20:47 UTC by matthew-levan

Resolves #492.

2023-07-12 20:49 UTC, matthew-levan commented
Where is the best place to add a helper function to determine which identity type (comet, moon, planet, star, galaxy) we are, given `c3_d *who_d`? We need such a function to set the new "forwarding enabled" flag `sat_u.for_o` in the `u3_ames` struct.

2023-07-12 21:32 UTC, philipcmonk commented
So far we've just done `u3do("clan:title", u3k(ship))`.  Wouldn't be hard to add a clan function (especially if we need to call it before the loom is set up), not sure where it fits, maybe vortex.c?

2023-07-12 23:45 UTC, matthew-levan commented
Thanks @philipcmonk. How's this look now?

2023-07-13 00:27 UTC, philipcmonk commented on pkg/vere/io/ames.c
> +    if ( _(sam_u->sat_u.for_o) ) {
I think we mostly do `== c3y` instead of `_` because it's a bit clearer.

2023-07-13 00:29 UTC, philipcmonk requested changes

2023-07-13 00:29 UTC, philipcmonk commented on pkg/vere/io/ames.c
> +  u3_noun rac = u3do("clan:title", u3k(who));
`who` is leaked here.  Probably easiest to just remove the `u3k` to transfer it into `u3do`

2023-07-13 20:18 UTC, philipcmonk approved these changes
Looks good!

2023-07-14 00:22 UTC, merged