build: fetch `urcrypt` instead of vendoring it
urbit/vere pull request #524
Opened 2023-09-27 01:27 UTC by matthew-levan

As [`urcrypt`](https://github.com/urbit/urcrypt) now has its own repository, we can stop vendoring it and simply fetch it like any of our other third-party dependencies.

2023-11-09 19:55 UTC, joemfb submitted a review, later dismissed
this will do

2023-11-09 19:55 UTC, joemfb commented
@matthew-levan I seem to recall there being some question about the urcrypt header pattern here; has that been resolved? if so, feel free to merge.

2023-11-10 00:22 UTC, matthew-levan commented
> @matthew-levan I seem to recall there being some question about the urcrypt header pattern here; has that been resolved? if so, feel free to merge.

Yea there were, but I never got around to resolving them. Looks like the build is working though in CI-- should we just merge and punt on the header particulars?

2023-11-13 16:39 UTC, joemfb commented
This fails on my machine:

```
Makefile.am: installing 'build-aux/depcomp'
Makefile.am:23: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined
autoreconf: error: automake failed with exit status: 1
```

2023-11-13 17:02 UTC, matthew-levan commented
Ok, I don't get that error on my Mac. Which system are you using? Do you
have `/usr/local/include/urcrypt.h` installed? Which command produced that
stack trace? Thanks.

On Mon, Nov 13, 2023 at 11:39 AM Joe Bryan ***@***.***> wrote:

> This fails on my machine:
>
> Makefile.am: installing 'build-aux/depcomp'
> Makefile.am:23: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined
> autoreconf: error: automake failed with exit status: 1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/vere/pull/524#issuecomment-1808524804>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2DQRB7DRBD36XCVI23KBTYEJEL5AVCNFSM6AAAAAA5ISE2PWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBYGUZDIOBQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-13 17:10 UTC, matthew-levan commented
Ok, thanks. Which version of macOS and which hardware?

On Mon, Nov 13, 2023 at 12:07 PM Joe Bryan ***@***.***> wrote:

> I don't have a /usr/local/include directory. I checked out your branch
> and ran bazel build --clang_version=14.0.0 :urbit.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/vere/pull/524#issuecomment-1808600808>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2DQRBZJGANNYAHP2VOMDTYEJHVBAVCNFSM6AAAAAA5ISE2PWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBYGYYDAOBQHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-13 18:05 UTC, joemfb commented
MacOS 12.6.1. 2021 Macbook Pro (m1 max)

2023-11-13 19:57 UTC, matthew-levan commented
Maybe you have to install `pkg-config`. Do you have
`/usr/local/lib/pkgconfig` or `/usr/lib/pkgconfig`?

On Mon, Nov 13, 2023 at 1:05 PM Joe Bryan ***@***.***> wrote:

> MacOS 12.6.1. 2021 Macbook Pro (m1 max)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/vere/pull/524#issuecomment-1808725314>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2DQRGCGWPSMEVCTKRJLKLYEJOOXAVCNFSM6AAAAAA5ISE2PWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBYG4ZDKMZRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-15 14:41 UTC, joemfb commented
After installing pkg-config via homebrew, i get a new error:

```
libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/external/aes_siv -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/aes_siv -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/openssl/openssl/include -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/urcrypt/urcrypt.ext_build_deps/openssl/include -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/urcrypt/urcrypt.ext_build_deps/secp256k1/include -march=native -std=c11 -Wextra -Wpedantic -Wall -Wall -g -O3 -MT keccak-tiny/libkeccak_tiny_la-keccak-tiny.lo -MD -MP -MF keccak-tiny/.deps/libkeccak_tiny_la-keccak-tiny.Tpo -c keccak-tiny/keccak-tiny.c -o keccak-tiny/libkeccak_tiny_la-keccak-tiny.o
clang: error: the clang compiler does not support '-march=native'
make[1]: *** [keccak-tiny/libkeccak_tiny_la-keccak-tiny.lo] Error 1
```

2023-11-15 14:44 UTC, matthew-levan commented
Strange. Will try to look later. Are you planning to upgrade your Mac?
Perhaps that might fix it.

On Wed, Nov 15, 2023 at 9:41 AM Joe Bryan ***@***.***> wrote:

> After installing pkg-config via homebrew, i get a new error:
>
> libtool: compile:  /usr/bin/clang -DHAVE_CONFIG_H -I. -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/external/aes_siv -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/aes_siv -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/openssl/openssl/include -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/urcrypt/urcrypt.ext_build_deps/openssl/include -I/private/var/tmp/_bazel_joemfb/f46182e3eb1bf4d7eff53357bd650651/sandbox/darwin-sandbox/3/execroot/__main__/bazel-out/darwin_arm64-opt/bin/external/urcrypt/urcrypt.ext_build_deps/secp256k1/include -march=native -std=c11 -Wextra -Wpedantic -Wall -Wall -g -O3 -MT keccak-tiny/libkeccak_tiny_la-keccak-tiny.lo -MD -MP -MF keccak-tiny/.deps/libkeccak_tiny_la-keccak-tiny.Tpo -c keccak-tiny/keccak-tiny.c -o keccak-tiny/libkeccak_tiny_la-keccak-tiny.o
> clang: error: the clang compiler does not support '-march=native'
> make[1]: *** [keccak-tiny/libkeccak_tiny_la-keccak-tiny.lo] Error 1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/vere/pull/524#issuecomment-1812663217>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2DQRBWI7LBLVYABAMRSDLYETIB5AVCNFSM6AAAAAA5ISE2PWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJSGY3DGMRRG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-15 18:29 UTC, joemfb commented
This now works on my machine, but is broken on linux in CI.

Also, can you update INSTALL.md to mention the new pkg-config dependency for macos?

2023-11-15 20:49 UTC, matthew-levan commented
Ok I fixed the build, and it should work with compilers that don't support `-march=native` also.

2023-11-15 21:03 UTC, joemfb commented
After this update, the build failed with

```
error: possibly undefined macro: AC_MSG_NOTICE
```

After i installed autoconf-archive from homebrew, it builds correctly.

2023-11-15 21:04 UTC, joemfb requested changes

2023-11-15 21:04 UTC, matthew-levan commented on INSTALL.md
> +After installing `automake`, `autoconf-archive`, and `libtool`, you're ready to build Vere.
tyty

2023-11-15 21:10 UTC, joemfb approved these changes
this will do

2023-11-15 21:26 UTC, merged