BLAKE3 jets
urbit/vere pull request #535
Opened 2023-10-07 23:59 UTC by lukechampine

See https://github.com/urbit/urbit/pull/6802 and https://github.com/urbit/urcrypt/pull/8

Depends on https://github.com/urbit/vere/pull/524

2023-10-08 00:22 UTC, lukechampine commented
Anyone on a beefy amd64 machine want to benchmark this? I'm on an M2, so I can't see those juicy AVX-512 speedups. 😭 Still, ~1.2 GB/s ain't bad -- that's 2x faster than sha3, and 4x faster than blake2b.

2023-10-17 19:33 UTC, belisarius222 commented
It looks like there's some git churn here.  Maybe merge develop into your branch?

2023-11-26 20:03 UTC, lukechampine commented on pkg/noun/jets/e/blake.c
> +      return u3i_cell(u3i_bytes(32, cv_y), u3i_qual(u3i_chub(counter_d), u3i_bytes(64, block_y), block_len, u3i_bytes(1, &flags_y)));
worth defining `u3i_quil`? 🤔

2023-12-07 18:03 UTC, joemfb requested changes
These look good. I've noted a couple issues with one allocation, and an assertion that should be removed.

These jets will go into 411 (or later), so they should not be declared in the hoon %140 cores. I've setup the declarations for 411 (hoon 138) in #567, it'll be simplest for this PR to target that one.

2024-01-25 21:17 UTC, joemfb approved these changes
this will do

2024-01-25 21:18 UTC, merged