Automatically create GitHub releases
urbit/vere pull request #59
Opened 2023-01-09 22:12 UTC by matthew-levan

Resolves #57.

2023-01-17 19:35 UTC, matthew-levan commented
Is this still necessary? If not, please close it.

2023-01-18 02:58 UTC, sethfork commented
A common pattern of behavior is checking releases on `urbit/urbit`. It now seems `vere` is the place to go, which is fine - it would just be good to continue actually doing releases. If there's no technical reason to block this, it should be accepted.

2023-01-18 16:17 UTC, sethfork requested changes

2023-01-18 16:17 UTC, sethfork commented on .github/workflows/shared.yml
> +            git tag urbit-v$version
Rename tag from `urbit-v$version` to `vere-v$version`

2023-01-18 16:17 UTC, sethfork commented on .github/workflows/shared.yml
> +            gh release create urbit-v$version \
Use `vere-v$version` for GH release

2023-01-18 16:17 UTC, sethfork commented on .github/workflows/shared.yml
> +          gh release upload urbit-v$version ${{ matrix.target }}.tgz
Likewise, switch `urbit` to `vere` here

2023-01-18 19:02 UTC, matthew-levan commented
I have some updates here but I can't push to my original feature branch since being removed from the `urbit` organization on GH. I'll push once I get re-added, or just fork the repo if it takes too long.

2023-01-19 16:44 UTC, matthew-levan commented
Closing in favor of #136.

2023-01-19 16:44 UTC, closed without merging